### ISSUE TITLE
decimal episodes support

### ISSUE THREAD

**Issue by Evan-aja** [ksyasuda/aniwrapper#2]
Good morning, is it possible to give the script support for decimal episodes?

I've noticed that the script isn't able to download nor stream episode 7.5 of saihate no paladin. It doesn't even shows up on rofi. I haven't tested this on ani-cli. But since this uses ani-cli as its base, I figure that pystardust's ani-cli would've done the same thing.

Thanks in advance

**Comment by ksyasuda** [comment]
Thanks for bringing this to my attention, the feature has now been implemented (not updated in the README yet though)

I'm still working on getting the half episode to show up in the episode list.  However, you can now select a half episode (like episode 7.5 of saihate no paladin) if you know it exists by prepending a `h` to the episode number

In your case entering `h7` into the episode selection menu will bring up episode `7.5`
