### ISSUE TITLE
How to change default theme?

### ISSUE THREAD

**Issue by wiscaksono** [ksyasuda/aniwrapper#3]
i tried to change theme directly from the aniwrapper, but when i reopen aniwrapper the theme always change to default.

**Comment by ksyasuda** [comment]
I would suggest instead that you create an alias that uses the `-t` flag
For example: `alias aniwrapper='aniwrapper -t dracula'`

After running the code in the example above (or putting the alias in the `.bashrc` to make it persistent), any time `aniwrapper` is run, it will actually run `aniwrapper -t dracula` and launch with the `dracula` theme

**Comment by ksyasuda** [comment]
If you really don't want to set an alias or just prefer to edit the source code, then here are the edits that need to be made:
There are 3 variables that need to be changed in `aniwrapper`: `CFG_FILE`, `ROFI_THEME`, and `theme`
- The first two variables, `CFG_FILE` and `ROFI_THEME`, are the path and filename of the theme
- The `theme` variable is one of `$THEMES`: `alter|aniwrapper|dracula|doomone|fancy|material|monokai|nord|nord2|onedark`

![image](https://user-images.githubusercontent.com/33813108/160955784-865ac9bc-c132-4b09-8c7a-baa586b383a2.png)
