### ISSUE TITLE
Inability to handle part based episodes correctly

### ISSUE THREAD

**Issue by mathgeniuszach** [ksyasuda/aniwrapper#7]
When attempting to view the episodes for honzuki-no-gekokujou-shisho-ni-naru-tame-ni-wa-shudan-wo-erandeiraremasen-3rd-season (Ascendance of a Bookworm season 3), the player gets confused at parts one and two of episode 0.5.
The only error message is as follows:
![image](https://user-images.githubusercontent.com/40220050/174751409-5e008916-5a7e-4fdd-a03e-27d7984f0e00.png)
And no episode list is shown:
![Screenshot_2022-06-21_04-20-52](https://user-images.githubusercontent.com/40220050/174752503-b710f857-276f-469f-8dea-54f3f1a83eaf.png)
I can still view episodes besides those two segmented episodes by specifying the exact number.

**Comment by ksyasuda** [comment]
Thanks for bringing this to my attention.  Support for .5 episodes was dropped some time back and this must have slipped through the cracks during the recent updates to the scaping logic

I've updated the code to ignore the .5 episodes so it will display correctly in the menu
![rofi-2022-06-25-1907-00000](https://user-images.githubusercontent.com/33813108/175796373-e471c6eb-b71e-4aca-b1bf-98121fd123c5.png)

**Comment by mathgeniuszach** [comment]
Not exactly the solution I'd like to see, but it is far better than it was before.
